assets:
  settings.xml: yegor256/home#assets/sttc/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
  secring.gpg: yegor256/home#assets/secring.gpg
  s3cfg: yegor256/home#assets/s3cfg
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
install:
- sudo gem install pdd
merge:
  script:
  - mvn clean install -Pqulice --errors --settings ../settings.xml
  - mvn clean
  - pdd --source=$(pwd) --verbose --file=/dev/null
  commanders:
  - yegor256
deploy:
  script:
  - mvn clean deploy -Pqulice --errors --settings ../settings.xml
  - mvn clean
  - pdd --source=$(pwd) --verbose --file=sttc-java-sdk.xml
  - s3cmd --no-progress put sttc-java-sdk.xml --config=../s3cfg s3://pdd.teamed.io/sttc-java-sdk.xml
  commanders:
  - yegor256
release:
  script:
  - mvn versions:set "-DnewVersion=${tag}"
  - git commit -am "${tag}"
  - mvn clean deploy -Pqulice -Psonatype -Psttc --errors --settings ../settings.xml
  - mvn clean site-deploy -Psite --errors --settings ../settings.xml
  commanders:
  - yegor256
architect:
- karato
- yegor256