assets:
  settings.xml: "yegor256/home#assets/sttc/settings.xml"
  pubring.gpg: "yegor256/home#assets/pubring.gpg"
  secring.gpg: "yegor256/home#assets/secring.gpg"

merge:
  script: 
    - "mvn clean install -Pqulice --errors --settings ../settings.xml"

deploy:
  script: 
    - "mvn clean deploy -Ppdd -Pqulice --errors --settings ../settings.xml"

release:
  script: 
    - "mvn versions:set \"-DnewVersion=${tag}\""
    - "git commit -am \"${tag}\""
    - "mvn clean deploy -Pqulice -Psonatype -Psttc --errors --settings ../settings.xml"
    - "mvn clean site-deploy -Psite -Prempl --errors --settings ../settings.xml"
