assets:
  settings.xml: yegor256/home#assets/sttc/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
  secring.gpg: yegor256/home#assets/secring.gpg
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
install:
- sudo gem install pdd -v 0.20.5
merge:
  script: |-
    pdd -f /dev/null
    mvn clean install -Pqulice --errors --settings ../settings.xml
deploy:
  script: |-
    pdd -f /dev/null
    mvn clean deploy -Pqulice --errors --settings ../settings.xml
release:
  script: |-
    pdd -f /dev/null
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean site-deploy -Psite --errors --settings ../settings.xml
    mvn clean deploy -Pqulice -Psonatype -Psttc --errors --settings ../settings.xml
