# SPDX-FileCopyrightText: Copyright (c) 2014-2025, stateful.co
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/rultor-image:1.21.0
assets:
  settings.xml: yegor256/home#assets/sttc/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
  secring.gpg: yegor256/home#assets/secring.gpg
merge:
  script: |-
    pdd -f /dev/null
    mvn clean install -Pqulice --errors --settings ../settings.xml
release:
  pre: false
  script: |-
    pdd -f /dev/null
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    # mvn clean site-deploy -Psite --errors --settings ../settings.xml
    mvn clean deploy -Pqulice -Psonatype -Psttc --errors --settings ../settings.xml
